language: go

services:
  - docker

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?$/

stages:
  - style
  - test
  - goreportcard

jobs:
  include:
    - stage: style
      name: "gofmt"
      script: diff -u <(echo -n) <(gofmt -d -s .)
    - name: "golint"
      install: go get -u golang.org/x/lint/golint
      script: golint -set_exit_status ./...
    - name: "govet"
      script: go vet ./...
    - stage: test
      before_install:
        - docker pull quay.io/keycloak/keycloak
        - docker run -d -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=secret -e KEYCLOAK_IMPORT=/tmp/gocloak-realm.json -v "`pwd`/testdata/gocloak-realm.json:/tmp/gocloak-realm.json" -p 8080:8080 --name keycloak quay.io/keycloak/keycloak -Dkeycloak.profile.feature.upload_scripts=enabled
      script:
        - go test -cover -race -coverprofile=coverage.txt -covermode=atomic
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      after_failure:
        - docker ps
        - docker logs keycloak
    - stage: goreportcard
      script: curl --fail --request POST "https://goreportcard.com/checks" --data "repo=github.com/Nerzal/gocloak"
      if: branch = master AND type = push
    - stage: nancy
      before_script:
      - cd /tmp && mkdir tools && cd -
      - sudo curl -s -L "https://github.com/sonatype-nexus-community/nancy/releases/download/0.0.39/nancy-linux.amd64-0.0.39" -o "/tmp/tools/nancy"
      - sudo chmod +x /tmp/tools/nancy
      script: 
      - nancy /tmp/tools/nancygo.sum
